### ISSUE TITLE
로그인 페이지 UI 구현

### ISSUE THREAD

**Issue by dbstjrrb12** [salpinoff/salpinoff_FE#9]
- [x] 사용자 닉네임 입력 Form UI 개발 
- [ ] 사용자 감정 & 스트레스 설정 UI 개발 
- [ ] 몬스터 닉네임 및 사연 입력 Form UI 개발 

## 공통 컴포넌트 
- [x] BaseButton 컴포넌트 개발
- [x] ModalButton 컴포넌트 개발 
- [x] Spinner 컴포넌트 개발

**Comment by emayom** [comment]
> - [ ] 몬스터 꾸미기 UI 개발
> - [ ] 몬스터 생성 완료 UI (공유하기 버튼 등) 개발

분배를 위해 별도의 이슈로 분리하였습니다~!
